-- Permit tech / HOA tech rosters are no longer fixed at exactly 3 slots —
-- organizations.permit_tech_seats / hoa_tech_seats (30_org_role_seats... see
-- 31_org_role_seats.sql) now control the real count, generated by
-- permitTechSlots()/hoaTechSlots() in src/lib/inventory/constants.ts and
-- src/lib/hoa/constants.ts. This loosens the old 3-value enumerated CHECK
-- on org_tech_names.slot (which only ever allowed exactly "Permit Tech
-- 1/2/3" or "Tech 1/2/3") to a format check instead — any positive slot
-- number is now a valid row shape at the DB level. The actual per-org cap
-- (does this org really have that many seats) is enforced in the app, in
-- src/lib/actions/tech-names.ts and src/lib/actions/team.ts, since that's
-- the only place with both the org's seat count and the slot in hand.

alter table org_tech_names drop constraint if exists org_tech_names_slot_check;
alter table org_tech_names add constraint org_tech_names_slot_check check (
  (kind = 'permit' and slot ~ '^Permit Tech [1-9][0-9]*$')
  or (kind = 'hoa' and slot ~ '^Tech [1-9][0-9]*$')
);
