/**
 * Captures the exact "Download Floor Plan PDF" output of the ezPermitBuilder
 * tool (public/floor-plan-creator.html) for the Permit Package ZIP, without
 * touching that file at all. It loads the tool headlessly in the same way
 * FloorPlanEmbed does (same URL params, so its own cloud-load logic runs
 * unmodified), then temporarily overrides jsPDF's `save()` inside that
 * iframe's window to capture the generated bytes instead of triggering a
 * browser download, and clicks the tool's own "Download Floor Plan PDF"
 * button to produce them. The override is removed and the iframe is
 * discarded immediately after.
 */

interface JsPdfInstance {
  output: (type: "blob") => Blob;
  save: (fileName?: string) => void;
}

type JsPdfCtor = new (...args: unknown[]) => JsPdfInstance;

interface FloorPlanWindow extends Window {
  jspdf?: { jsPDF: JsPdfCtor };
}

export async function captureFloorPlanPdf(params: {
  supabaseUrl: string;
  supabaseAnonKey: string;
  accessToken: string;
  orgId: string;
  jobId: string;
  timeoutMs?: number;
}): Promise<Uint8Array | null> {
  const timeoutMs = params.timeoutMs ?? 15000;
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.top = "-10000px";
  iframe.style.left = "0px";
  iframe.style.width = "1600px";
  iframe.style.height = "1000px";
  iframe.style.border = "0";
  const qs = new URLSearchParams({
    sb_url: params.supabaseUrl,
    sb_key: params.supabaseAnonKey,
    access_token: params.accessToken,
    org_id: params.orgId,
    job_id: params.jobId,
  });
  iframe.src = `/floor-plan-creator.html?${qs.toString()}`;

  document.body.appendChild(iframe);

  try {
    await new Promise<void>((resolve, reject) => {
      const onLoad = () => resolve();
      iframe.addEventListener("load", onLoad, { once: true });
      setTimeout(() => reject(new Error("timeout loading floor plan tool")), timeoutMs);
    });

    const win = iframe.contentWindow as FloorPlanWindow | null;
    const doc = iframe.contentDocument;
    if (!win || !doc) return null;

    // Wait for the tool's own cloud-load status text to settle (it fetches
    // the job's saved floor_plans row on init and writes a status string).
    const statusEl = doc.getElementById("cloud-save-status");
    const deadline = Date.now() + timeoutMs;
    while (statusEl && !statusEl.textContent && Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 150));
    }
    // Give the canvas one more tick to finish drawing after state applies.
    await new Promise((r) => setTimeout(r, 300));

    const pdfBtn = doc.getElementById("pdf-btn") as HTMLButtonElement | null;
    if (!pdfBtn || !win.jspdf) return null;

    // jsPDF (v2.5.1 UMD) attaches `save()` as an OWN property on each
    // document instance inside its constructor (its plugin-API pattern
    // merges API methods onto `this`), not onto `jsPDF.prototype` — so
    // patching the prototype is a no-op. Instead we wrap the `jsPDF`
    // constructor itself: once the tool's click handler does
    // `new jsPDF(...)`, we intercept right after construction and replace
    // that instance's own `save` with our capture function, before the
    // handler's later `doc.save('floor-plan.pdf')` call runs.
    const jspdfNs = win.jspdf;
    const OriginalJsPDF = jspdfNs.jsPDF;
    let settled = false;
    let capturedBlobResolve: ((b: Blob | null) => void) | null = null;
    const blobPromise = new Promise<Blob | null>((resolve) => {
      capturedBlobResolve = resolve;
    });
    function WrappedJsPDF(this: unknown, ...args: unknown[]) {
      const instance = new OriginalJsPDF(...args);
      instance.save = () => {
        if (settled) return;
        settled = true;
        jspdfNs.jsPDF = OriginalJsPDF;
        try {
          capturedBlobResolve?.(instance.output("blob"));
        } catch {
          capturedBlobResolve?.(null);
        }
      };
      return instance;
    }
    WrappedJsPDF.prototype = OriginalJsPDF.prototype;
    jspdfNs.jsPDF = WrappedJsPDF as unknown as JsPdfCtor;

    pdfBtn.click();

    const raced = await Promise.race([
      blobPromise,
      new Promise<null>((resolve) => setTimeout(() => resolve(null), 8000)),
    ]);
    if (!settled) {
      settled = true;
      jspdfNs.jsPDF = OriginalJsPDF;
    }

    if (!raced) return null;
    return new Uint8Array(await raced.arrayBuffer());
  } catch {
    return null;
  } finally {
    iframe.remove();
  }
}
