"use client";

import { createElement as h, useState } from "react";
import { requestService } from "./actions";

const FIELD =
  "mt-1 block w-full rounded-2xl border border-border bg-background px-3 py-2 text-sm text-foreground";
  const BTN =
    "inline-flex h-11 items-center justify-center rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground";

    const SOURCES = [
      { value: "sales", label: "Sales" },
        { value: "install", label: "Install board" },
          { value: "permit", label: "Permit" },
            { value: "hoa", label: "HOA" },
              { value: "manager", label: "Management" },
                { value: "service", label: "Service" },
                ];

                export function ServiceRequestForm({
                  mail,
                    defaultSource,
                      next,
                      }: {
                        mail?: string;
                          defaultSource?: string;
                            next?: string;
                            }) {
                              const [isNewJob, setIsNewJob] = useState(false);

                                return h(
                                    "div",
                                        { className: "mx-auto max-w-xl space-y-5" },
                                            h(
                                                  "div",
                                                        null,
                                                              h("h1", { className: "font-heading text-2xl font-semibold tracking-tight" }, "Request service"),
                                                                    h(
                                                                            "p",
                                                                                    { className: "text-sm text-muted-foreground" },
                                                                                            "Pull an existing job number, or add one that isn't in PermitAIO yet.",
                                                                                                  ),
                                                                                                      ),
                                                                                                          mail ? h("p", { className: "text-sm text-emerald-700" }, mail) : null,
                                                                                                              h(
                                                                                                                    "form",
                                                                                                                          { action: requestService, className: "space-y-4" },
                                                                                                                                h("input", { type: "hidden", name: "next", value: next || "/service?app=request" }),
                                                                                                                                      h(
                                                                                                                                              "label",
                                                                                                                                                      { className: "block text-sm font-medium" },
                                                                                                                                                              "Requesting as",
                                                                                                                                                                      h(
                                                                                                                                                                                "select",
                                                                                                                                                                                          { name: "requestSource", defaultValue: defaultSource || "service", className: FIELD },
                                                                                                                                                                                                    SOURCES.map((s) => h("option", { key: s.value, value: s.value }, s.label)),
                                                                                                                                                                                                            ),
                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                        h(
                                                                                                                                                                                                                                "label",
                                                                                                                                                                                                                                        { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                "Job number",
                                                                                                                                                                                                                                                        h("input", {
                                                                                                                                                                                                                                                                  name: "jobNumber",
                                                                                                                                                                                                                                                                            required: true,
                                                                                                                                                                                                                                                                                      autoComplete: "off",
                                                                                                                                                                                                                                                                                                placeholder: "92300-1",
                                                                                                                                                                                                                                                                                                          className: `${FIELD} font-mono`,
                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                              h(
                                                                                                                                                                                                                                                                                                                                      "label",
                                                                                                                                                                                                                                                                                                                                              { className: "flex items-center gap-2 text-sm" },
                                                                                                                                                                                                                                                                                                                                                      h("input", {
                                                                                                                                                                                                                                                                                                                                                                type: "checkbox",
                                                                                                                                                                                                                                                                                                                                                                          name: "isNewJob",
                                                                                                                                                                                                                                                                                                                                                                                    checked: isNewJob,
                                                                                                                                                                                                                                                                                                                                                                                              onChange: () => setIsNewJob((v) => !v),
                                                                                                                                                                                                                                                                                                                                                                                                        className: "h-4 w-4 rounded border-input",
                                                                                                                                                                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                                                                                                                                                                        "Not in PermitAIO yet (new sale or pre-onboarding job)",
                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                    isNewJob
                                                                                                                                                                                                                                                                                                                                                                                                                                            ? h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "div",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { className: "space-y-3 rounded-2xl border p-3" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "label",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Client name",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h("input", { name: "clientName", required: isNewJob, className: FIELD }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "label",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Address",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h("input", { name: "address", className: FIELD }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                h("label", { className: "block text-sm font-medium" }, "City", h("input", { name: "city", className: FIELD })),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "label",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "What does the job need?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h("textarea", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name: "issueDescription",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      minLength: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder: "Leak, glass, hardware, callback, new install visit…",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className: `${FIELD} min-h-24`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "div",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { className: "grid gap-3 sm:grid-cols-2" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "label",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Priority",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "select",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { name: "priority", defaultValue: "routine", className: FIELD },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            h("option", { value: "routine" }, "Routine"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        h("option", { value: "urgent" }, "Urgent"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  h(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "label",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { className: "block text-sm font-medium" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Preferred date (optional)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          h("input", { type: "date", name: "requestedDate", className: FIELD }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              h("button", { type: "submit", className: BTN }, "Send request"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
