export type Question = {
  id: string;
  section: string;
  prompt: string;
  hint: string;
  placeholder: string;
};

export const QUESTIONS: Question[] = [
  {
    id: "name",
    section: "The person on the phone",
    prompt: "What name should it use?",
    hint: "An employee introduces themselves. This is the name callers will remember.",
    placeholder: "Alex, with Majestic",
  },
  {
    id: "greeting",
    section: "The person on the phone",
    prompt: "What is the first sentence when it picks up?",
    hint: "Say it the way you want a new caller to hear it.",
    placeholder: "Majestic and PermitAIO, this is Alex.",
  },
  {
    id: "if-human",
    section: "The person on the phone",
    prompt: "If they ask “are you a real person?”, what should it say?",
    hint: "Do not have it pretend. Write the exact line.",
    placeholder: "I'm the scheduling assistant. I can book you with Angelique.",
  },
  {
    id: "tone",
    section: "The person on the phone",
    prompt: "How should it sound?",
    hint: "Short and direct, warm, or formal. Add anything it should never sound like.",
    placeholder: "Calm and short. No sales pitch. No jokes.",
  },
  {
    id: "which-line",
    section: "The person on the phone",
    prompt: "Which calls does it answer?",
    hint: "Majestic, PermitAIO, or both. Say what it does if they reached the wrong one.",
    placeholder: "Both. If they only want one, stay on that one.",
  },
  {
    id: "you",
    section: "The person on the phone",
    prompt: "Who is the person it books for, and how should it refer to you?",
    hint: "Name, role, and whether it says “she”, “the owner”, or your first name.",
    placeholder: "Angelique. She runs both companies.",
  },

  {
    id: "majestic-sentence",
    section: "What an employee knows cold",
    prompt: "In one sentence, what is Majestic Construction Permits?",
    hint: "The sentence a new hire would memorize.",
    placeholder: "We pull the permits for window, door, and roofing contractors.",
  },
  {
    id: "majestic-who",
    section: "What an employee knows cold",
    prompt: "Who is Majestic for, and who is it not for?",
    hint: "Trade, size of shop, and anyone you turn away.",
    placeholder: "South Florida contractors who want the permit handled for them.",
  },
  {
    id: "majestic-does",
    section: "What an employee knows cold",
    prompt: "What does Majestic do on a job, from the day they hire you to the day it is done?",
    hint: "Write the steps in order. This is the service, not the software.",
    placeholder: "We take the job, build the package, submit, answer the city, and stay on it through inspection.",
  },
  {
    id: "majestic-not",
    section: "What an employee knows cold",
    prompt: "What does Majestic not do?",
    hint: "Install, sell the windows, engineer, HOA for them, or whatever is out of bounds.",
    placeholder: "We do not install. We do not sell the product.",
  },
  {
    id: "aio-sentence",
    section: "What an employee knows cold",
    prompt: "In one sentence, what is PermitAIO?",
    hint: "Say what it is. If it is not a CRM, say that here.",
    placeholder: "The permit operating system. One job number from measure to inspection.",
  },
  {
    id: "aio-who",
    section: "What an employee knows cold",
    prompt: "Which trades is PermitAIO for right now?",
    hint: "Name the ones you sell, and the ones you do not.",
    placeholder: "Windows and doors first. Roofing. Not a general contractor tool.",
  },
  {
    id: "aio-path",
    section: "What an employee knows cold",
    prompt: "Walk the software the way an employee would. What happens to one job, desk by desk?",
    hint: "Measure, permit, HOA, order, warehouse, install, inspection. Only the desks you want said out loud.",
    placeholder: "Sales looks up the job. Permit builds the package. HOA clears the association. Warehouse checks the product. Install schedules only when permit and HOA are clear.",
  },
  {
    id: "tell-apart",
    section: "What an employee knows cold",
    prompt: "How do you tell if they want Majestic or PermitAIO?",
    hint: "The words a caller uses, and the one question the assistant should ask if it is not sure.",
    placeholder: "If they want us to pull it, Majestic. If they want the system for their own office, PermitAIO.",
  },

  {
    id: "before-submit",
    section: "How a job moves",
    prompt: "What has to be true before a permit is submitted?",
    hint: "What an employee checks. Plans, NOA, forms, contractor info, HOA, engineering.",
    placeholder: "Floor plan, sizes, product approvals, and the city's forms.",
  },
  {
    id: "before-order",
    section: "How a job moves",
    prompt: "What has to be true before materials are ordered?",
    hint: "Permit status, HOA, deposit, or whatever you actually wait for.",
    placeholder: "Permit approved, or written okay from the office.",
  },
  {
    id: "before-install",
    section: "How a job moves",
    prompt: "What has to be true before install is scheduled?",
    hint: "An employee does not put a crew on a job that is not clear.",
    placeholder: "Permit and HOA both clear. Product checked in.",
  },
  {
    id: "permit-statuses",
    section: "How a job moves",
    prompt: "List the permit statuses an employee may say, and what each one means in plain words.",
    hint: "Only statuses you use. One per line. If they name one that is not here, the assistant must not invent it.",
    placeholder: "Need to Submit — not in yet.\nIn Review — the city has it.\nApproved — issued or ready to print.",
  },
  {
    id: "job-statuses",
    section: "How a job moves",
    prompt: "List the job statuses an employee may say, and what each one means.",
    hint: "The board statuses, not the permit pill. Engineering, ordered, ready, and so on.",
    placeholder: "Engineering Review — drawings are out.\nOrdered — product is on order.",
  },
  {
    id: "numbers",
    section: "How a job moves",
    prompt: "What is a job number, and what is a permit number? How should it ask for each?",
    hint: "An employee never mixes these up. Write the question it should ask.",
    placeholder: "Job number is ours. Permit number is the city's. Ask: do you have our job number, or the city's permit number?",
  },
  {
    id: "counties",
    section: "How a job moves",
    prompt: "Which counties and cities do you cover?",
    hint: "Name them. This is the map an employee is allowed to talk about.",
    placeholder: "Broward, Miami-Dade, Palm Beach.",
  },
  {
    id: "outside",
    section: "How a job moves",
    prompt: "If the city is one you do not cover, what should it say?",
    hint: "Exact sentence. Then book a demo, or end the call.",
    placeholder: "We work Broward, Miami-Dade, and Palm Beach. I can still book a demo if you are opening there.",
  },

  {
    id: "who-calls",
    section: "Sales",
    prompt: "Who usually calls, and what do they want in the first minute?",
    hint: "Owner, office manager, permit tech. What they are stuck on.",
    placeholder: "The owner. They are tired of permits sitting.",
  },
  {
    id: "problem",
    section: "Sales",
    prompt: "What problem should it say back, in one sentence?",
    hint: "An employee reflects the pain. They do not pitch yet.",
    placeholder: "Your office is chasing the city instead of running jobs.",
  },
  {
    id: "next-step",
    section: "Sales",
    prompt: "What is the one next step you want from every new caller?",
    hint: "A demo, a callback, or a start packet. Only one.",
    placeholder: "Book a 20-minute demo.",
  },
  {
    id: "qualify",
    section: "Sales",
    prompt: "What should it ask to know if they are a fit?",
    hint: "Trade, county, how many jobs a month, who pulls permits now. List the questions.",
    placeholder: "What do you install? Which counties? About how many permits a month?",
  },
  {
    id: "not-a-fit",
    section: "Sales",
    prompt: "Who is not a fit, and what should it say to them?",
    hint: "Homeowners, out-of-state, a trade you do not take.",
    placeholder: "Homeowners. Tell them we work with the contractor, and offer the contractor's number if they have one.",
  },
  {
    id: "free-paid",
    section: "Sales",
    prompt: "What is free, and what do they get only after they pay?",
    hint: "Write it the way an employee is allowed to say it. No extras.",
    placeholder: "They can try the floor plan. NOAs, the schedule, and the package are on the paid plan.",
  },
  {
    id: "price",
    section: "Sales",
    prompt: "What price may it say? Write the exact words, or write “no price on the phone.”",
    hint: "Separate Majestic and PermitAIO if the prices differ.",
    placeholder: "No price on the phone. The demo covers it.",
  },
  {
    id: "trial",
    section: "Sales",
    prompt: "Is there a trial? What is in it, and how long?",
    hint: "If there is no trial, say that.",
    placeholder: "No trial. They see the demo, then they decide.",
  },
  {
    id: "different",
    section: "Sales",
    prompt: "When they ask how you are different, what should it say?",
    hint: "Two or three sentences an employee can repeat without inventing.",
    placeholder: "One job number. The next person gets the work when the last step clears.",
  },
  {
    id: "never-promise",
    section: "Sales",
    prompt: "What must it never promise on a sales call?",
    hint: "Dates, approval, a price, a city outcome, a hire.",
    placeholder: "Never promise the city will approve it. Never promise a start date.",
  },

  {
    id: "hours",
    section: "Booking the demo",
    prompt: "What days and hours may it book? Eastern.",
    hint: "An employee does not offer times you will not take.",
    placeholder: "Weekdays, 10 to 4.",
  },
  {
    id: "length",
    section: "Booking the demo",
    prompt: "How long is the demo, and is it a phone call or a video call?",
    hint: "Say which link or number they will use, if you want that said.",
    placeholder: "20 minutes. Phone.",
  },
  {
    id: "collect",
    section: "Booking the demo",
    prompt: "What must it get before it books?",
    hint: "Name, company, phone, email, trade, county. Cross off anything you do not need.",
    placeholder: "Name, company, phone, trade, and the county they work in.",
  },
  {
    id: "calendar",
    section: "Booking the demo",
    prompt: "Whose calendar, and what should the event be called?",
    hint: "Also what belongs in the notes.",
    placeholder: "Angelique's calendar. Title: Demo — company name. Notes: trade, county, Majestic or PermitAIO.",
  },
  {
    id: "after-book",
    section: "Booking the demo",
    prompt: "After it books, what should it tell them?",
    hint: "Repeat the day and time. Say if they should open the demo first, and which one.",
    placeholder: "You're set for Tuesday at 11. Look at permitaio.com before we talk. Nothing there is saved.",
  },
  {
    id: "no-demo",
    section: "Booking the demo",
    prompt: "If they do not want a demo, or nothing is open, what should it say?",
    hint: "Then it should end the call. Write both lines.",
    placeholder: "No problem. If you want to look first, the demos are on permitaio.com.",
  },

  {
    id: "start-steps",
    section: "Onboarding",
    prompt: "After they say yes, what are the steps, in order?",
    hint: "What an employee walks them through. Number them.",
    placeholder: "1. Agreement. 2. Their login. 3. Their products and NOAs. 4. First job.",
  },
  {
    id: "need-from-them",
    section: "Onboarding",
    prompt: "What do you need from them before the first job?",
    hint: "License, insurance, product list, forms, who the permit tech is.",
    placeholder: "License, insurance, the products they use, and a person who will run the permit desk.",
  },
  {
    id: "they-do",
    section: "Onboarding",
    prompt: "What do they set up themselves, and what do you set up for them?",
    hint: "An employee should not offer to do the part that is theirs.",
    placeholder: "They load their own product library. We open the company and the logins.",
  },
  {
    id: "login",
    section: "Onboarding",
    prompt: "What does their login include on day one?",
    hint: "Their company only. Which desks. What they will not see.",
    placeholder: "Their jobs, their NOAs, their forms. Not another contractor's work.",
  },
  {
    id: "how-long",
    section: "Onboarding",
    prompt: "How long from yes to the first job in the system?",
    hint: "A real range. Do not let it promise tomorrow if that is not true.",
    placeholder: "A few days, once we have their license and product list.",
  },
  {
    id: "ready",
    section: "Onboarding",
    prompt: "How does a shop know they are ready?",
    hint: "The check an employee uses. First job opened, first package, first login.",
    placeholder: "They can open a job, place the openings, and see their own schedule.",
  },
  {
    id: "after-signup",
    section: "Onboarding",
    prompt: "Who contacts them after they start, and how?",
    hint: "You, an email, a text. What that first message says.",
    placeholder: "I email the login the same day the agreement is back.",
  },

  {
    id: "pull-it",
    section: "Permit inquiries",
    prompt: "If they ask “can you pull my permit?”, what should it say?",
    hint: "Majestic answer and PermitAIO answer, if they differ.",
    placeholder: "Majestic: yes, that is the service, let's book it. PermitAIO: your office pulls it in the system. I can show you on a demo.",
  },
  {
    id: "already-in",
    section: "Permit inquiries",
    prompt: "If a permit is already in process, what should it ask for?",
    hint: "Job number, permit number, address, city. What it does with those. It should not guess a status.",
    placeholder: "Ask for the job number first. If they only have the city's number, take that and a callback number. Do not give a status.",
  },
  {
    id: "lookup",
    section: "Permit inquiries",
    prompt: "Can it look up a live job, or only take a message?",
    hint: "Be exact. An employee does not open the file unless you say it can.",
    placeholder: "Message only. It cannot see the jobs.",
  },
  {
    id: "permit-number-given",
    section: "Permit inquiries",
    prompt: "If they give a permit number on the call, what should it do with it?",
    hint: "Write it down for you, repeat it back, or tell them to bring it to the demo.",
    placeholder: "Repeat it back, put it in the calendar notes, and do not change anything.",
  },
  {
    id: "city-comment",
    section: "Permit inquiries",
    prompt: "If they read a city comment or a correction, what should it do?",
    hint: "Listen, write it down, book you. It should not explain the code.",
    placeholder: "Write down the city and the comment in their words. Tell them you will cover it on the demo. Do not interpret it.",
  },
  {
    id: "safe-answers",
    section: "Permit inquiries",
    prompt: "Which permit questions are safe to answer? Write the question and your answer.",
    hint: "Only answers you would let a new employee give with no one in the room.",
    placeholder: "How long does Broward take? — It varies. We do not quote a city timeline.",
  },
  {
    id: "wait-for-you",
    section: "Permit inquiries",
    prompt: "Which permit questions must always wait for you?",
    hint: "Forms, NOA choice, a rejection, a fee, a status on a live job.",
    placeholder: "Which form to use. Which NOA. Why the city rejected it. Any live status.",
  },
  {
    id: "hoa",
    section: "Permit inquiries",
    prompt: "If they ask about an HOA, what should an employee say?",
    hint: "Whether you handle associations, what you need, and what you will not promise.",
    placeholder: "We track the HOA on the same job. We do not promise the association will approve it.",
  },
  {
    id: "inspection",
    section: "Permit inquiries",
    prompt: "If they ask about an inspection, what should it say?",
    hint: "Who schedules it, what has to be ready, and what it must not promise.",
    placeholder: "Inspection is after the permit is issued and the work is in. We do not book the inspector on this call.",
  },
  {
    id: "form-noa",
    section: "Permit inquiries",
    prompt: "If they ask which form or which NOA to use, what should it say?",
    hint: "This is where employees get in trouble by guessing. Write the refusal.",
    placeholder: "That depends on the product and the city. Bring the product to the demo. I will not guess a form.",
  },
  {
    id: "failed",
    section: "Permit inquiries",
    prompt: "If they have a failed inspection or a rejection, what should it say?",
    hint: "Take the city, the comment, and a number. Do not diagnose it.",
    placeholder: "I'm sorry. Tell me the city and what they wrote. Angelique will look at the wording. I won't guess the fix.",
  },

  {
    id: "contract-now",
    section: "Hand it to you",
    prompt: "If they want a contract or a proposal on the phone, what should it say?",
    hint: "An employee does not negotiate terms on the call.",
    placeholder: "The demo is where we go through that. I can book it.",
  },
  {
    id: "talk-now",
    section: "Hand it to you",
    prompt: "If they want you right now, what should it say?",
    hint: "When it may interrupt you, and when it only books.",
    placeholder: "She is with a job. I can book the next open time, or take a number if it is a city deadline today.",
  },
  {
    id: "same-day",
    section: "Hand it to you",
    prompt: "What makes a call worth you calling back the same day?",
    hint: "A city deadline, a signed shop, an angry client. Be specific.",
    placeholder: "A permit expiring, a failed inspection, or a shop ready to start this week.",
  },
  {
    id: "after-call",
    section: "Hand it to you",
    prompt: "What should you receive after every call, and where?",
    hint: "A summary, the recording, an email. Say what must be in the summary.",
    placeholder: "Email me: who called, Majestic or PermitAIO, what they wanted, and the time you booked.",
  },
  {
    id: "dont-know",
    section: "Hand it to you",
    prompt: "When it does not know, what is the one sentence it uses every time?",
    hint: "Then it books or takes a message. It does not fill the gap.",
    placeholder: "I don't want to guess that. I'll have Angelique cover it on the demo.",
  },
  {
    id: "never",
    section: "Hand it to you",
    prompt: "What must it never say or do?",
    hint: "The rules you would fire an employee for breaking.",
    placeholder: "Never invent a status, a form, a price, or a city rule. Never say a permit is approved.",
  },
  {
    id: "else",
    section: "Hand it to you",
    prompt: "What else would a trained employee know that is not in the questions above?",
    hint: "Phrases you use, shops you will not name, a rule you repeat every week.",
    placeholder: "Job number is the only number that matters until the city issues theirs.",
  },
];
